apiVersion: v1                          # Kubernetes API version
kind: Namespace                         # Type of resource (Namespace)
metadata:
  name: cloudshop-prod                 # Name of this namespace
  labels:
    name: cloudshop-prod               # Label for easy filtering
    environment: production            # Another label